/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gametrpl.View;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ROG
 */
public class dealer extends javax.swing.JFrame {

    /**
     * Creates new form dealer
     */
    public dealer() {
        initComponents();
    }

    public JButton getB_bank() {
        return b_bank;
    }

    public JButton getB_dealer() {
        return b_dealer;
    }

    public JButton getB_nextTurn() {
        return b_nextTurn;
    }

    public JButton getB_property() {
        return b_property;
    }

    public JButton getB_usaha() {
        return b_usaha;
    }

    public JButton getBeliKendaraan1() {
        return beliKendaraan1;
    }

    public JButton getBeliKendaraan2() {
        return beliKendaraan2;
    }

    public JButton getBeliKendaraan3() {
        return beliKendaraan3;
    }

    public JButton getBeliKendaraan4() {
        return beliKendaraan4;
    }

    public JButton getBeliKendaraan5() {
        return beliKendaraan5;
    }

    public JButton getBeliKendaraan6() {
        return beliKendaraan6;
    }

    public JButton getBeliKendaraan7() {
        return beliKendaraan7;
    }

    public JButton getBeliKendaraan8() {
        return beliKendaraan8;
    }

    public JButton getB_beli() {
        return b_beli;
    }

    public void setB_beli(JButton b_beli) {
        this.b_beli = b_beli;
    }

    public JLabel getDanaTxt() {
        return danaTxt;
    }

    public JLabel getPenghasilanTxt() {
        return penghasilanTxt;
    }

    public JLabel getKendaraanTxt() {
        return kendaraanTxt;
    }

    public JLabel getPropertyTxt() {
        return propertyTxt;
    }

    public JLabel getJmlh1() {
        return jmlh1;
    }

    public JLabel getJmlh2() {
        return jmlh2;
    }

    public JLabel getJmlh3() {
        return jmlh3;
    }

    public JLabel getJmlh4() {
        return jmlh4;
    }

    public JLabel getJmlh5() {
        return jmlh5;
    }

    public JLabel getJmlh6() {
        return jmlh6;
    }

    public JLabel getJmlh7() {
        return jmlh7;
    }

    public JLabel getJmlh8() {
        return jmlh8;
    }

    public JLabel getTurnTxt() {
        return turnTxt;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmlh1 = new javax.swing.JLabel();
        jmlh2 = new javax.swing.JLabel();
        jmlh3 = new javax.swing.JLabel();
        jmlh4 = new javax.swing.JLabel();
        jmlh5 = new javax.swing.JLabel();
        jmlh6 = new javax.swing.JLabel();
        jmlh7 = new javax.swing.JLabel();
        jmlh8 = new javax.swing.JLabel();
        turnTxt = new javax.swing.JLabel();
        danaTxt = new javax.swing.JLabel();
        penghasilanTxt = new javax.swing.JLabel();
        kendaraanTxt = new javax.swing.JLabel();
        propertyTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b_nextTurn = new javax.swing.JButton();
        b_usaha = new javax.swing.JButton();
        b_bank = new javax.swing.JButton();
        b_dealer = new javax.swing.JButton();
        b_property = new javax.swing.JButton();
        beliKendaraan1 = new javax.swing.JButton();
        beliKendaraan2 = new javax.swing.JButton();
        beliKendaraan3 = new javax.swing.JButton();
        beliKendaraan4 = new javax.swing.JButton();
        beliKendaraan5 = new javax.swing.JButton();
        beliKendaraan6 = new javax.swing.JButton();
        beliKendaraan7 = new javax.swing.JButton();
        beliKendaraan8 = new javax.swing.JButton();
        b_beli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jmlh1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmlh1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlh1.setText("0");
        getContentPane().add(jmlh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 40, 80));

        jmlh2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmlh2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlh2.setText("0");
        getContentPane().add(jmlh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 40, 80));

        jmlh3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmlh3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlh3.setText("0");
        getContentPane().add(jmlh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 40, 80));

        jmlh4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmlh4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlh4.setText("0");
        getContentPane().add(jmlh4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 50, 80));

        jmlh5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmlh5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlh5.setText("0");
        getContentPane().add(jmlh5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, 50, 80));

        jmlh6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmlh6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlh6.setText("0");
        getContentPane().add(jmlh6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 50, 80));

        jmlh7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmlh7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlh7.setText("0");
        getContentPane().add(jmlh7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 390, 50, 80));

        jmlh8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmlh8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlh8.setText("0");
        getContentPane().add(jmlh8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 510, 40, 80));

        turnTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        turnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnTxt.setText("0");
        getContentPane().add(turnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 110, 40));
        getContentPane().add(danaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 16, 150, 30));
        getContentPane().add(penghasilanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 150, 20));

        kendaraanTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kendaraanTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kendaraanTxt.setText("0");
        getContentPane().add(kendaraanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 30, 30));

        propertyTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        propertyTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertyTxt.setText("0");
        getContentPane().add(propertyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametrpl/gambar/Halaman Motor Motor.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 750));

        b_nextTurn.setText("next turn");
        b_nextTurn.setBorderPainted(false);
        b_nextTurn.setContentAreaFilled(false);
        getContentPane().add(b_nextTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 130, 130));

        b_usaha.setText("usaha");
        b_usaha.setBorderPainted(false);
        b_usaha.setContentAreaFilled(false);
        b_usaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_usahaActionPerformed(evt);
            }
        });
        getContentPane().add(b_usaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 150, 130));

        b_bank.setText("bank");
        b_bank.setBorderPainted(false);
        b_bank.setContentAreaFilled(false);
        getContentPane().add(b_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 140, 130));

        b_dealer.setText("dealer");
        b_dealer.setBorderPainted(false);
        b_dealer.setContentAreaFilled(false);
        getContentPane().add(b_dealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 150, 130));

        b_property.setText("property");
        b_property.setBorderPainted(false);
        b_property.setContentAreaFilled(false);
        getContentPane().add(b_property, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 130, 130));

        beliKendaraan1.setText("jButton1");
        beliKendaraan1.setBorderPainted(false);
        beliKendaraan1.setContentAreaFilled(false);
        getContentPane().add(beliKendaraan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 80, 80));

        beliKendaraan2.setText("jButton1");
        beliKendaraan2.setBorderPainted(false);
        beliKendaraan2.setContentAreaFilled(false);
        getContentPane().add(beliKendaraan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 80, 80));

        beliKendaraan3.setText("jButton1");
        beliKendaraan3.setBorderPainted(false);
        beliKendaraan3.setContentAreaFilled(false);
        getContentPane().add(beliKendaraan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 80, 80));

        beliKendaraan4.setText("jButton1");
        beliKendaraan4.setBorderPainted(false);
        beliKendaraan4.setContentAreaFilled(false);
        getContentPane().add(beliKendaraan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 80, 80));

        beliKendaraan5.setText("jButton1");
        beliKendaraan5.setBorderPainted(false);
        beliKendaraan5.setContentAreaFilled(false);
        getContentPane().add(beliKendaraan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, 90));

        beliKendaraan6.setText("jButton1");
        beliKendaraan6.setBorderPainted(false);
        beliKendaraan6.setContentAreaFilled(false);
        getContentPane().add(beliKendaraan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 80, 80));

        beliKendaraan7.setText("jButton1");
        beliKendaraan7.setBorderPainted(false);
        beliKendaraan7.setContentAreaFilled(false);
        getContentPane().add(beliKendaraan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 80, 80));

        beliKendaraan8.setText("jButton1");
        beliKendaraan8.setBorderPainted(false);
        beliKendaraan8.setContentAreaFilled(false);
        getContentPane().add(beliKendaraan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 80, 80));

        b_beli.setText("jButton1");
        b_beli.setBorderPainted(false);
        b_beli.setContentAreaFilled(false);
        getContentPane().add(b_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 220, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_usahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_usahaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_usahaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dealer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_bank;
    private javax.swing.JButton b_beli;
    private javax.swing.JButton b_dealer;
    private javax.swing.JButton b_nextTurn;
    private javax.swing.JButton b_property;
    private javax.swing.JButton b_usaha;
    private javax.swing.JButton beliKendaraan1;
    private javax.swing.JButton beliKendaraan2;
    private javax.swing.JButton beliKendaraan3;
    private javax.swing.JButton beliKendaraan4;
    private javax.swing.JButton beliKendaraan5;
    private javax.swing.JButton beliKendaraan6;
    private javax.swing.JButton beliKendaraan7;
    private javax.swing.JButton beliKendaraan8;
    private javax.swing.JLabel danaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jmlh1;
    private javax.swing.JLabel jmlh2;
    private javax.swing.JLabel jmlh3;
    private javax.swing.JLabel jmlh4;
    private javax.swing.JLabel jmlh5;
    private javax.swing.JLabel jmlh6;
    private javax.swing.JLabel jmlh7;
    private javax.swing.JLabel jmlh8;
    private javax.swing.JLabel kendaraanTxt;
    private javax.swing.JLabel penghasilanTxt;
    private javax.swing.JLabel propertyTxt;
    private javax.swing.JLabel turnTxt;
    // End of variables declaration//GEN-END:variables
}
