/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gametrpl.View;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ROG
 */
public class halamanBankKalku extends javax.swing.JFrame {

    /**
     * Creates new form halamanBankKalku
     */
    public halamanBankKalku() {
        initComponents();
    }

    public JButton getB_bank() {
        return b_bank;
    }

    public JButton getB_dealer() {
        return b_dealer;
    }

//    public JButton getB_hitung() {
//        return b_hitung;
//    }

    public JButton getB_nextTurn() {
        return b_nextTurn;
    }

    public JButton getB_pinjam() {
        return b_pinjam;
    }

    public JButton getB_property() {
        return b_property;
    }

    public JButton getB_usaha() {
        return b_usaha;
    }

    public JButton getB_kalkulasi() {
        return b_kalkulasi;
    }

    public JLabel getBungaBulananText() {
        return bungaBulananText;
    }

    public JTextField getPinjamanTxt() {
        return pinjamanTxt;
    }

    public JLabel getPokokPlusBungaText() {
        return pokokPlusBungaText;
    }

    public JTextField getSukuBunga() {
        return sukuBunga;
    }

    public ButtonGroup getTenor() {
        return tenor;
    }

    public JRadioButton getTenor1() {
        return tenor1;
    }

    public JRadioButton getTenor2() {
        return tenor2;
    }

    public JRadioButton getTenor3() {
        return tenor3;
    }

    public JRadioButton getTenor4() {
        return tenor4;
    }

    public JLabel getDanaTxt() {
        return danaTxt;
    }

    public JLabel getKendaraanTxt() {
        return kendaraanTxt;
    }

    public JLabel getPenghasilanTxt() {
        return penghasilanTxt;
    }

    public JLabel getTurnTxt() {
        return turnTxt;
    }

    public JLabel getPropertyTxt() {
        return propertyTxt;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenor = new javax.swing.ButtonGroup();
        pinjamanTxt = new javax.swing.JTextField();
        sukuBunga = new javax.swing.JTextField();
        tenor1 = new javax.swing.JRadioButton();
        tenor2 = new javax.swing.JRadioButton();
        tenor3 = new javax.swing.JRadioButton();
        tenor4 = new javax.swing.JRadioButton();
        pokokPlusBungaText = new javax.swing.JLabel();
        bungaBulananText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        danaTxt = new javax.swing.JLabel();
        penghasilanTxt = new javax.swing.JLabel();
        propertyTxt = new javax.swing.JLabel();
        kendaraanTxt = new javax.swing.JLabel();
        turnTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        b_nextTurn = new javax.swing.JButton();
        b_usaha = new javax.swing.JButton();
        b_bank = new javax.swing.JButton();
        b_dealer = new javax.swing.JButton();
        b_property = new javax.swing.JButton();
        b_pinjam = new javax.swing.JButton();
        b_kalkulasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pinjamanTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(pinjamanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 440, 37));

        sukuBunga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(sukuBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 140, 37));

        tenor.add(tenor1);
        tenor1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tenor1.setText("12 Turn");
        tenor1.setContentAreaFilled(false);
        getContentPane().add(tenor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        tenor.add(tenor2);
        tenor2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tenor2.setText("24 Turn");
        tenor2.setContentAreaFilled(false);
        getContentPane().add(tenor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        tenor.add(tenor3);
        tenor3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tenor3.setText("36 Turn");
        tenor3.setContentAreaFilled(false);
        getContentPane().add(tenor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        tenor.add(tenor4);
        tenor4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tenor4.setText("48 Turn");
        tenor4.setContentAreaFilled(false);
        getContentPane().add(tenor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        pokokPlusBungaText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pokokPlusBungaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pokokPlusBungaText.setText("0");
        getContentPane().add(pokokPlusBungaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 210, 40));

        bungaBulananText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bungaBulananText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bungaBulananText.setText("0");
        getContentPane().add(bungaBulananText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 210, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("%");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, 40));

        danaTxt.setText("800");
        getContentPane().add(danaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 20, 150, 30));

        penghasilanTxt.setText("40");
        getContentPane().add(penghasilanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 150, 30));

        propertyTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        propertyTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertyTxt.setText("0");
        getContentPane().add(propertyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        kendaraanTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kendaraanTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kendaraanTxt.setText("0");
        getContentPane().add(kendaraanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 30, 30));

        turnTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        turnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnTxt.setText("0");
        getContentPane().add(turnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 120, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Angsuran per Bulan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Kalkulator Angsuran");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Jumlah Pinjaman");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Suku Bunga Per Tahun");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Lama Peminjaman");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Bunga per Bulan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametrpl/gambar/Halaman Jaminan.png"))); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(1050, 780));
        jLabel15.setMinimumSize(new java.awt.Dimension(1050, 780));
        jLabel15.setPreferredSize(new java.awt.Dimension(1050, 780));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        b_nextTurn.setText("next turn");
        b_nextTurn.setBorderPainted(false);
        b_nextTurn.setContentAreaFilled(false);
        getContentPane().add(b_nextTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 22, 130, 130));

        b_usaha.setText("jButton1");
        b_usaha.setBorderPainted(false);
        b_usaha.setContentAreaFilled(false);
        getContentPane().add(b_usaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 92, 140, 130));

        b_bank.setText("jButton1");
        b_bank.setBorderPainted(false);
        b_bank.setContentAreaFilled(false);
        getContentPane().add(b_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 237, 150, 140));

        b_dealer.setText("jButton1");
        b_dealer.setBorderPainted(false);
        b_dealer.setContentAreaFilled(false);
        getContentPane().add(b_dealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 150, 140));

        b_property.setText("jButton1");
        b_property.setBorderPainted(false);
        b_property.setContentAreaFilled(false);
        getContentPane().add(b_property, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 537, 150, 140));

        b_pinjam.setText("jButton1");
        b_pinjam.setBorderPainted(false);
        b_pinjam.setContentAreaFilled(false);
        getContentPane().add(b_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 674, 170, 60));

        b_kalkulasi.setText("Kalkulasi");
        b_kalkulasi.setBorderPainted(false);
        b_kalkulasi.setContentAreaFilled(false);
        getContentPane().add(b_kalkulasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 680, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanBankKalku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanBankKalku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanBankKalku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanBankKalku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanBankKalku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_bank;
    private javax.swing.JButton b_dealer;
    private javax.swing.JButton b_kalkulasi;
    private javax.swing.JButton b_nextTurn;
    private javax.swing.JButton b_pinjam;
    private javax.swing.JButton b_property;
    private javax.swing.JButton b_usaha;
    private javax.swing.JLabel bungaBulananText;
    private javax.swing.JLabel danaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel kendaraanTxt;
    private javax.swing.JLabel penghasilanTxt;
    private javax.swing.JTextField pinjamanTxt;
    private javax.swing.JLabel pokokPlusBungaText;
    private javax.swing.JLabel propertyTxt;
    private javax.swing.JTextField sukuBunga;
    private javax.swing.ButtonGroup tenor;
    private javax.swing.JRadioButton tenor1;
    private javax.swing.JRadioButton tenor2;
    private javax.swing.JRadioButton tenor3;
    private javax.swing.JRadioButton tenor4;
    private javax.swing.JLabel turnTxt;
    // End of variables declaration//GEN-END:variables
}
