/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gametrpl.View;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ROG
 */
public class halamanBankAwal extends javax.swing.JFrame {

    /**
     * Creates new form halamanBank1
     */
    public halamanBankAwal() {
        initComponents();
    }

    public JButton getB_bank() {
        return b_bank;
    }

    public void setB_bank(JButton b_bank) {
        this.b_bank = b_bank;
    }

    public JButton getB_dealer() {
        return b_dealer;
    }

    public void setB_dealer(JButton b_dealer) {
        this.b_dealer = b_dealer;
    }

    public JButton getB_hitung() {
        return b_hitung;
    }

    public void setB_hitung(JButton b_hitung) {
        this.b_hitung = b_hitung;
    }

    public JButton getB_nextTurn() {
        return b_nextTurn;
    }

    public void setB_nextTurn(JButton b_nextTurn) {
        this.b_nextTurn = b_nextTurn;
    }

    public JButton getB_pinjam() {
        return b_pinjam;
    }

    public void setB_pinjam(JButton b_pinjam) {
        this.b_pinjam = b_pinjam;
    }

    public JButton getB_property() {
        return b_property;
    }

    public void setB_property(JButton b_property) {
        this.b_property = b_property;
    }

    public JButton getB_usaha() {
        return b_usaha;
    }

    public void setB_usaha(JButton b_usaha) {
        this.b_usaha = b_usaha;
    }

    public JLabel getDanaTxt() {
        return danaTxt;
    }

    public JLabel getKendaraanTxt() {
        return kendaraanTxt;
    }

    public JLabel getPenghasilanTxt() {
        return penghasilanTxt;
    }

    public JLabel getPropertyTxt() {
        return propertyTxt;
    }

    public JLabel getTurnTxt() {
        return turnTxt;
    }
    
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        danaTxt = new javax.swing.JLabel();
        penghasilanTxt = new javax.swing.JLabel();
        turnTxt = new javax.swing.JLabel();
        kendaraanTxt = new javax.swing.JLabel();
        propertyTxt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        b_usaha = new javax.swing.JButton();
        b_bank = new javax.swing.JButton();
        b_dealer = new javax.swing.JButton();
        b_property = new javax.swing.JButton();
        b_pinjam = new javax.swing.JButton();
        b_nextTurn = new javax.swing.JButton();
        b_hitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 780));
        setMinimumSize(new java.awt.Dimension(1050, 780));
        setPreferredSize(new java.awt.Dimension(1050, 780));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        danaTxt.setText("800");
        getContentPane().add(danaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 20, 150, 30));

        penghasilanTxt.setText("40");
        getContentPane().add(penghasilanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 150, 30));

        turnTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        turnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnTxt.setText("0");
        getContentPane().add(turnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 120, 50));

        kendaraanTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kendaraanTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kendaraanTxt.setText("0");
        getContentPane().add(kendaraanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 30, 30));

        propertyTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        propertyTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertyTxt.setText("0");
        getContentPane().add(propertyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametrpl/gambar/Halaman Jaminan.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        b_usaha.setText("jButton1");
        b_usaha.setBorderPainted(false);
        b_usaha.setContentAreaFilled(false);
        getContentPane().add(b_usaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 150, 140));

        b_bank.setText("jButton1");
        b_bank.setBorderPainted(false);
        b_bank.setContentAreaFilled(false);
        getContentPane().add(b_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, 127));

        b_dealer.setText("jButton1");
        b_dealer.setBorderPainted(false);
        b_dealer.setContentAreaFilled(false);
        getContentPane().add(b_dealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 397, 150, 130));

        b_property.setText("jButton1");
        b_property.setBorderPainted(false);
        b_property.setContentAreaFilled(false);
        getContentPane().add(b_property, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 132, 127));

        b_pinjam.setText("pinjam");
        b_pinjam.setBorderPainted(false);
        b_pinjam.setContentAreaFilled(false);
        getContentPane().add(b_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 674, 170, 50));

        b_nextTurn.setText("next turn");
        b_nextTurn.setBorderPainted(false);
        b_nextTurn.setContentAreaFilled(false);
        getContentPane().add(b_nextTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 130, 130));

        b_hitung.setText("Hitung");
        b_hitung.setToolTipText("");
        b_hitung.setBorderPainted(false);
        b_hitung.setContentAreaFilled(false);
        getContentPane().add(b_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 674, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanBankAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanBankAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanBankAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanBankAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanBankAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_bank;
    private javax.swing.JButton b_dealer;
    private javax.swing.JButton b_hitung;
    private javax.swing.JButton b_nextTurn;
    private javax.swing.JButton b_pinjam;
    private javax.swing.JButton b_property;
    private javax.swing.JButton b_usaha;
    private javax.swing.JLabel danaTxt;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel kendaraanTxt;
    private javax.swing.JLabel penghasilanTxt;
    private javax.swing.JLabel propertyTxt;
    private javax.swing.JLabel turnTxt;
    // End of variables declaration//GEN-END:variables
}
