/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gametrpl.View;

import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROG
 */
public class halamanBankJaminan extends javax.swing.JFrame {

    /**
     * Creates new form halamanBankJaminan
     */
    public halamanBankJaminan() {
        initComponents();
    }

    public JButton getB_bank() {
        return b_bank;
    }

    public void setB_bank(JButton b_bank) {
        this.b_bank = b_bank;
    }

    public JButton getB_dealer() {
        return b_dealer;
    }

    public void setB_dealer(JButton b_dealer) {
        this.b_dealer = b_dealer;
    }

    public JButton getB_hitung() {
        return b_hitung;
    }

    public void setB_hitung(JButton b_hitung) {
        this.b_hitung = b_hitung;
    }

    public JButton getB_nextTurn() {
        return b_nextTurn;
    }

    public void setB_nextTurn(JButton b_nextTurn) {
        this.b_nextTurn = b_nextTurn;
    }

    public JButton getB_pinjam() {
        return b_pinjam;
    }

    public void setB_pinjam(JButton b_pinjam) {
        this.b_pinjam = b_pinjam;
    }

    public JButton getB_property() {
        return b_property;
    }

    public void setB_property(JButton b_property) {
        this.b_property = b_property;
    }

    public JButton getB_usaha() {
        return b_usaha;
    }

    public void setB_usaha(JButton b_usaha) {
        this.b_usaha = b_usaha;
    }

    public JTable getTabelKendaraanJ() {
        return tabelKendaraanJ;
    }

    public JTable getTabelPropertyJ() {
        return tabelPropertyJ;
    }

    public ButtonGroup getTenor() {
        return tenor;
    }

    public JRadioButton getTenor1() {
        return tenor1;
    }

    public JRadioButton getTenor2() {
        return tenor2;
    }

    public JRadioButton getTenor3() {
        return tenor3;
    }

    public JRadioButton getTenor4() {
        return tenor4;
    }

    public JButton getPilihJaminanK() {
        return pilihJaminanK;
    }

    public JButton getPilihJaminanP() {
        return pilihJaminanP;
    }

    public JLabel getMerkText() {
        return merkText;
    }

    public JLabel getDanaTxt() {
        return danaTxt;
    }

    public JLabel getKendaraanTxt() {
        return kendaraanTxt;
    }

    public JLabel getPenghasilanTxt() {
        return penghasilanTxt;
    }

    public JLabel getPinjamanText() {
        return pinjamanText;
    }

    public JLabel getPropertyTxt() {
        return propertyTxt;
    }

    public JLabel getTurnTxt() {
        return turnTxt;
    }

    public JButton getB_kembali() {
        return b_kembali;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenor = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPropertyJ = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelKendaraanJ = new javax.swing.JTable();
        tenor1 = new javax.swing.JRadioButton();
        tenor2 = new javax.swing.JRadioButton();
        tenor3 = new javax.swing.JRadioButton();
        tenor4 = new javax.swing.JRadioButton();
        merkText = new javax.swing.JLabel();
        pinjamanText = new javax.swing.JLabel();
        danaTxt = new javax.swing.JLabel();
        penghasilanTxt = new javax.swing.JLabel();
        propertyTxt = new javax.swing.JLabel();
        kendaraanTxt = new javax.swing.JLabel();
        turnTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        b_kembali = new javax.swing.JButton();
        pilihJaminanP = new javax.swing.JButton();
        pilihJaminanK = new javax.swing.JButton();
        b_nextTurn = new javax.swing.JButton();
        b_usaha = new javax.swing.JButton();
        b_bank = new javax.swing.JButton();
        b_dealer = new javax.swing.JButton();
        b_property = new javax.swing.JButton();
        b_pinjam = new javax.swing.JButton();
        b_hitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 790));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPropertyJ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipe", "Turn Pembelian", "Harga Jual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelPropertyJ);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 400, 280));

        tabelKendaraanJ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Merk ", "Tipe", "Turn Pembelian", "Harga Jual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelKendaraanJ);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 380, 280));

        tenor.add(tenor1);
        tenor1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tenor1.setText("12 Turn");
        tenor1.setContentAreaFilled(false);
        getContentPane().add(tenor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 590, -1, -1));

        tenor.add(tenor2);
        tenor2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tenor2.setText("24 Turn");
        tenor2.setContentAreaFilled(false);
        getContentPane().add(tenor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, -1, -1));

        tenor.add(tenor3);
        tenor3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tenor3.setText("36 Turn");
        tenor3.setContentAreaFilled(false);
        getContentPane().add(tenor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, -1, -1));

        tenor.add(tenor4);
        tenor4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tenor4.setText("48 Turn");
        tenor4.setContentAreaFilled(false);
        getContentPane().add(tenor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 590, -1, -1));

        merkText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(merkText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 250, 20));

        pinjamanText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(pinjamanText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 300, -1));

        danaTxt.setText("800");
        getContentPane().add(danaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 20, 150, 30));

        penghasilanTxt.setText("40");
        getContentPane().add(penghasilanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 150, 30));

        propertyTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        propertyTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertyTxt.setText("0");
        getContentPane().add(propertyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        kendaraanTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kendaraanTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kendaraanTxt.setText("0");
        getContentPane().add(kendaraanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 30, 30));

        turnTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        turnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnTxt.setText("0");
        getContentPane().add(turnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 120, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pinjaman : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Jaminan : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Lama Waktu Pembayaran :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametrpl/gambar/Pilih Jaminan.png"))); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(1050, 780));
        jLabel15.setMinimumSize(new java.awt.Dimension(1050, 780));
        jLabel15.setPreferredSize(new java.awt.Dimension(1050, 780));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        b_kembali.setText("jButton1");
        b_kembali.setBorderPainted(false);
        b_kembali.setContentAreaFilled(false);
        getContentPane().add(b_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 40));

        pilihJaminanP.setText("Pilih Jaminan");
        pilihJaminanP.setBorderPainted(false);
        pilihJaminanP.setContentAreaFilled(false);
        getContentPane().add(pilihJaminanP, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 170, 60));

        pilihJaminanK.setText("Pilih Jaminan");
        pilihJaminanK.setBorderPainted(false);
        pilihJaminanK.setContentAreaFilled(false);
        getContentPane().add(pilihJaminanK, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 170, 60));

        b_nextTurn.setText("next turn");
        b_nextTurn.setBorderPainted(false);
        b_nextTurn.setContentAreaFilled(false);
        getContentPane().add(b_nextTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 130, 130));

        b_usaha.setText("jButton1");
        b_usaha.setBorderPainted(false);
        b_usaha.setContentAreaFilled(false);
        getContentPane().add(b_usaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 132, 122));

        b_bank.setText("jButton1");
        b_bank.setBorderPainted(false);
        b_bank.setContentAreaFilled(false);
        getContentPane().add(b_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 132, 127));

        b_dealer.setText("jButton1");
        b_dealer.setBorderPainted(false);
        b_dealer.setContentAreaFilled(false);
        getContentPane().add(b_dealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 387, 140, 140));

        b_property.setText("jButton1");
        b_property.setBorderPainted(false);
        b_property.setContentAreaFilled(false);
        getContentPane().add(b_property, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 132, 127));

        b_pinjam.setText("jButton1");
        b_pinjam.setBorderPainted(false);
        b_pinjam.setContentAreaFilled(false);
        getContentPane().add(b_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, 170, 50));

        b_hitung.setText("jButton1");
        b_hitung.setBorderPainted(false);
        b_hitung.setContentAreaFilled(false);
        getContentPane().add(b_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, 160, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanBankJaminan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanBankJaminan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanBankJaminan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanBankJaminan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanBankJaminan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_bank;
    private javax.swing.JButton b_dealer;
    private javax.swing.JButton b_hitung;
    private javax.swing.JButton b_kembali;
    private javax.swing.JButton b_nextTurn;
    private javax.swing.JButton b_pinjam;
    private javax.swing.JButton b_property;
    private javax.swing.JButton b_usaha;
    private javax.swing.JLabel danaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel kendaraanTxt;
    private javax.swing.JLabel merkText;
    private javax.swing.JLabel penghasilanTxt;
    private javax.swing.JButton pilihJaminanK;
    private javax.swing.JButton pilihJaminanP;
    private javax.swing.JLabel pinjamanText;
    private javax.swing.JLabel propertyTxt;
    private javax.swing.JTable tabelKendaraanJ;
    private javax.swing.JTable tabelPropertyJ;
    private javax.swing.ButtonGroup tenor;
    private javax.swing.JRadioButton tenor1;
    private javax.swing.JRadioButton tenor2;
    private javax.swing.JRadioButton tenor3;
    private javax.swing.JRadioButton tenor4;
    private javax.swing.JLabel turnTxt;
    // End of variables declaration//GEN-END:variables
}
