/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gametrpl.View;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ROG
 */
public class halamanUsaha extends javax.swing.JFrame {

    /**
     * Creates new form halamanGame
     */
    public halamanUsaha() {
        initComponents();
    }

    public JButton getAa() {
        return aa;
    }

    public JButton getAb() {
        return ab;
    }

    public JButton getAc() {
        return ac;
    }

    public JButton getAd() {
        return ad;
    }

    public JButton getAe() {
        return ae;
    }

    public JButton getB_bank() {
        return b_bank;
    }

    public JButton getB_dealer() {
        return b_dealer;
    }

    public JButton getB_nextTurn() {
        return b_nextTurn;
    }

    public JButton getB_property() {
        return b_property;
    }

    public JButton getB_usaha() {
        return b_usaha;
    }

    public JButton getBa() {
        return ba;
    }

    public JButton getBb() {
        return bb;
    }

    public JButton getBc() {
        return bc;
    }

    public JButton getBd() {
        return bd;
    }

    public JButton getBe() {
        return be;
    }

    public JButton getCa() {
        return ca;
    }

    public JButton getCb() {
        return cb;
    }

    public JButton getCc() {
        return cc;
    }

    public JButton getCd() {
        return cd;
    }

    public JButton getCe() {
        return ce;
    }

    public JButton getDa() {
        return da;
    }

    public JButton getDb() {
        return db;
    }

    public JButton getDc() {
        return dc;
    }

    public JButton getDd() {
        return dd;
    }

    public JButton getDe() {
        return de;
    }

    public JLabel getG_usaha1() {
        return g_usaha1;
    }

    public JLabel getG_usaha2() {
        return g_usaha2;
    }

    public JLabel getG_usaha3() {
        return g_usaha3;
    }

    public JLabel getG_usaha4() {
        return g_usaha4;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_nextTurn = new javax.swing.JButton();
        b_usaha = new javax.swing.JButton();
        b_bank = new javax.swing.JButton();
        b_dealer = new javax.swing.JButton();
        b_property = new javax.swing.JButton();
        aa = new javax.swing.JButton();
        ab = new javax.swing.JButton();
        ac = new javax.swing.JButton();
        ad = new javax.swing.JButton();
        ae = new javax.swing.JButton();
        ba = new javax.swing.JButton();
        bb = new javax.swing.JButton();
        bc = new javax.swing.JButton();
        bd = new javax.swing.JButton();
        be = new javax.swing.JButton();
        ca = new javax.swing.JButton();
        cb = new javax.swing.JButton();
        cc = new javax.swing.JButton();
        cd = new javax.swing.JButton();
        ce = new javax.swing.JButton();
        da = new javax.swing.JButton();
        db = new javax.swing.JButton();
        dc = new javax.swing.JButton();
        dd = new javax.swing.JButton();
        de = new javax.swing.JButton();
        g_usaha1 = new javax.swing.JLabel();
        g_usaha2 = new javax.swing.JLabel();
        g_usaha3 = new javax.swing.JLabel();
        g_usaha4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_nextTurn.setText("next turn");
        getContentPane().add(b_nextTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 32, 90, 76));

        b_usaha.setText("usaha");
        getContentPane().add(b_usaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 96, 95));

        b_bank.setText("bank");
        getContentPane().add(b_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 222, 96, 95));

        b_dealer.setText("dealer");
        getContentPane().add(b_dealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 349, 96, 95));

        b_property.setText("property");
        getContentPane().add(b_property, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 96, 95));

        aa.setText("aa");
        getContentPane().add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, 38));

        ab.setText("ab");
        getContentPane().add(ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, 38));

        ac.setText("ac");
        getContentPane().add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, 38));

        ad.setText("ad");
        getContentPane().add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, 38));

        ae.setText("ae");
        getContentPane().add(ae, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, 38));

        ba.setText("ba");
        getContentPane().add(ba, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, 38));

        bb.setText("bb");
        getContentPane().add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, 38));

        bc.setText("bc");
        getContentPane().add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, 38));

        bd.setText("bd");
        getContentPane().add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, 38));

        be.setText("be");
        getContentPane().add(be, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, 38));

        ca.setText("ca");
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, 38));

        cb.setText("cb");
        getContentPane().add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, -1, 38));

        cc.setText("cc");
        getContentPane().add(cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, 38));

        cd.setText("cd");
        getContentPane().add(cd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, -1, 38));

        ce.setText("ce");
        getContentPane().add(ce, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, -1, 38));

        da.setText("ab");
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, -1, 38));

        db.setText("ab");
        getContentPane().add(db, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, -1, 38));

        dc.setText("ab");
        getContentPane().add(dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, 38));

        dd.setText("ab");
        getContentPane().add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, -1, 38));

        de.setText("bd");
        getContentPane().add(de, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, 38));

        g_usaha1.setText("usaha1");
        getContentPane().add(g_usaha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 90, 110));

        g_usaha2.setText("usaha2");
        getContentPane().add(g_usaha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 90, 110));

        g_usaha3.setText("usaha3");
        getContentPane().add(g_usaha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 90, 110));

        g_usaha4.setText("usaha4");
        getContentPane().add(g_usaha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 90, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanUsaha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanUsaha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanUsaha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanUsaha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanUsaha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aa;
    private javax.swing.JButton ab;
    private javax.swing.JButton ac;
    private javax.swing.JButton ad;
    private javax.swing.JButton ae;
    private javax.swing.JButton b_bank;
    private javax.swing.JButton b_dealer;
    private javax.swing.JButton b_nextTurn;
    private javax.swing.JButton b_property;
    private javax.swing.JButton b_usaha;
    private javax.swing.JButton ba;
    private javax.swing.JButton bb;
    private javax.swing.JButton bc;
    private javax.swing.JButton bd;
    private javax.swing.JButton be;
    private javax.swing.JButton ca;
    private javax.swing.JButton cb;
    private javax.swing.JButton cc;
    private javax.swing.JButton cd;
    private javax.swing.JButton ce;
    private javax.swing.JButton da;
    private javax.swing.JButton db;
    private javax.swing.JButton dc;
    private javax.swing.JButton dd;
    private javax.swing.JButton de;
    private javax.swing.JLabel g_usaha1;
    private javax.swing.JLabel g_usaha2;
    private javax.swing.JLabel g_usaha3;
    private javax.swing.JLabel g_usaha4;
    // End of variables declaration//GEN-END:variables
}
