/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gametrpl.View;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ROG
 */
public class halamanUsaha extends javax.swing.JFrame {

    /**
     * Creates new form halamanGame
     */
    public halamanUsaha() {
        initComponents();
    }

    public JButton getAa() {
        return aa;
    }

    public JButton getAb() {
        return ab;
    }

    public JButton getAc() {
        return ac;
    }

    public JButton getAd() {
        return ad;
    }

    public JButton getAe() {
        return ae;
    }

    public JButton getB_bank() {
        return b_bank;
    }

    public JButton getB_dealer() {
        return b_dealer;
    }

    public JButton getB_nextTurn() {
        return b_nextTurn;
    }

    public JButton getB_property() {
        return b_property;
    }

    public JButton getB_usaha() {
        return b_usaha;
    }

    public JButton getBa() {
        return ba;
    }

    public JButton getBb() {
        return bb;
    }

    public JButton getBc() {
        return bc;
    }

    public JButton getBd() {
        return bd;
    }

    public JButton getBe() {
        return be;
    }

    public JButton getCa() {
        return ca;
    }

    public JButton getCb() {
        return cb;
    }

    public JButton getCc() {
        return cc;
    }

    public JButton getCd() {
        return cd;
    }

    public JButton getCe() {
        return ce;
    }

    public JButton getDa() {
        return da;
    }

    public JButton getDb() {
        return db;
    }

    public JButton getDc() {
        return dc;
    }

    public JButton getDd() {
        return dd;
    }

    public JButton getDe() {
        return de;
    }

    public JLabel getDanaTxt() {
        return danaTxt;
    }
    
    public JLabel getPenghasilanTxt() {
        return penghasilanTxt;
    }

    public JButton getB_buatUsaha1() {
        return b_buatUsaha1;
    }

    public JButton getB_buatUsaha2() {
        return b_buatUsaha2;
    }

    public JButton getB_buatUsaha3() {
        return b_buatUsaha3;
    }

    public JButton getB_buatUsaha4() {
        return b_buatUsaha4;
    }

    public JLabel getTurnTxt() {
        return turnTxt;
    }

    public JLabel getModal1() {
        return modal1;
    }

    public JLabel getModal2() {
        return modal2;
    }

    public JLabel getModal3() {
        return modal3;
    }

    public JLabel getModal4() {
        return modal4;
    }

    public JLabel getOperasional1() {
        return operasional1;
    }

    public JLabel getOperasional2() {
        return operasional2;
    }

    public JLabel getOperasional3() {
        return operasional3;
    }

    public JLabel getOperasional4() {
        return operasional4;
    }

    public JLabel getPenghasilan1() {
        return penghasilan1;
    }

    public JLabel getPenghasilan2() {
        return penghasilan2;
    }

    public JLabel getPenghasilan3() {
        return penghasilan3;
    }

    public JLabel getPenghasilan4() {
        return penghasilan4;
    }

    public JLabel getU12txt() {
        return u12txt;
    }

    public JLabel getU13txt() {
        return u13txt;
    }

    public JLabel getU14txt() {
        return u14txt;
    }

    public JLabel getU15txt() {
        return u15txt;
    }

    public JLabel getU21txt() {
        return u21txt;
    }

    public JLabel getU22txt() {
        return u22txt;
    }

    public JLabel getU23txt() {
        return u23txt;
    }

    public JLabel getU24txt() {
        return u24txt;
    }

    public JLabel getU25txt() {
        return u25txt;
    }

    public JLabel getU31txt() {
        return u31txt;
    }

    public JLabel getU32txt() {
        return u32txt;
    }

    public JLabel getU33txt() {
        return u33txt;
    }

    public JLabel getU34txt() {
        return u34txt;
    }

    public JLabel getU35txt() {
        return u35txt;
    }

    public JLabel getU41txt() {
        return u41txt;
    }

    public JLabel getU42txt() {
        return u42txt;
    }

    public JLabel getU43txt() {
        return u43txt;
    }

    public JLabel getU44txt() {
        return u44txt;
    }

    public JLabel getU45txt() {
        return u45txt;
    }

    public JLabel getU11txt() {
        return u11txt;
    }

    public JLabel getKendaraanTxt() {
        return kendaraanTxt;
    }

    public JLabel getPropertyTxt() {
        return propertyTxt;
    }



    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fotokopi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        danaTxt = new javax.swing.JLabel();
        penghasilanTxt = new javax.swing.JLabel();
        turnTxt = new javax.swing.JLabel();
        operasional1 = new javax.swing.JLabel();
        penghasilan1 = new javax.swing.JLabel();
        modal1 = new javax.swing.JLabel();
        penghasilan2 = new javax.swing.JLabel();
        operasional2 = new javax.swing.JLabel();
        modal2 = new javax.swing.JLabel();
        penghasilan3 = new javax.swing.JLabel();
        operasional3 = new javax.swing.JLabel();
        modal3 = new javax.swing.JLabel();
        penghasilan4 = new javax.swing.JLabel();
        operasional4 = new javax.swing.JLabel();
        modal4 = new javax.swing.JLabel();
        u11txt = new javax.swing.JLabel();
        u12txt = new javax.swing.JLabel();
        u13txt = new javax.swing.JLabel();
        u15txt = new javax.swing.JLabel();
        u14txt = new javax.swing.JLabel();
        u21txt = new javax.swing.JLabel();
        u22txt = new javax.swing.JLabel();
        u23txt = new javax.swing.JLabel();
        u24txt = new javax.swing.JLabel();
        u25txt = new javax.swing.JLabel();
        u31txt = new javax.swing.JLabel();
        u33txt = new javax.swing.JLabel();
        u32txt = new javax.swing.JLabel();
        u34txt = new javax.swing.JLabel();
        u35txt = new javax.swing.JLabel();
        u41txt = new javax.swing.JLabel();
        u42txt = new javax.swing.JLabel();
        u43txt = new javax.swing.JLabel();
        u44txt = new javax.swing.JLabel();
        u45txt = new javax.swing.JLabel();
        kendaraanTxt = new javax.swing.JLabel();
        propertyTxt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        b_buatUsaha1 = new javax.swing.JButton();
        b_buatUsaha2 = new javax.swing.JButton();
        b_buatUsaha3 = new javax.swing.JButton();
        b_buatUsaha4 = new javax.swing.JButton();
        b_nextTurn = new javax.swing.JButton();
        b_usaha = new javax.swing.JButton();
        b_bank = new javax.swing.JButton();
        b_dealer = new javax.swing.JButton();
        b_property = new javax.swing.JButton();
        aa = new javax.swing.JButton();
        ab = new javax.swing.JButton();
        ac = new javax.swing.JButton();
        ad = new javax.swing.JButton();
        ae = new javax.swing.JButton();
        ba = new javax.swing.JButton();
        bb = new javax.swing.JButton();
        bc = new javax.swing.JButton();
        bd = new javax.swing.JButton();
        be = new javax.swing.JButton();
        ca = new javax.swing.JButton();
        cb = new javax.swing.JButton();
        cc = new javax.swing.JButton();
        cd = new javax.swing.JButton();
        ce = new javax.swing.JButton();
        da = new javax.swing.JButton();
        db = new javax.swing.JButton();
        dc = new javax.swing.JButton();
        dd = new javax.swing.JButton();
        de = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fotokopi.setText("Percetakan");
        getContentPane().add(Fotokopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, 30));

        jLabel4.setText("Minimarket");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, -1, 30));

        jLabel3.setText("Kedai Kopi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, -1, 30));

        jLabel2.setText("Laundry");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        danaTxt.setText("800");
        getContentPane().add(danaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 20, 150, 30));

        penghasilanTxt.setText("40");
        getContentPane().add(penghasilanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 150, 30));

        turnTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        turnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnTxt.setText("0");
        getContentPane().add(turnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 120, 50));
        getContentPane().add(operasional1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));
        getContentPane().add(penghasilan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));
        getContentPane().add(modal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));
        getContentPane().add(penghasilan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, -1, -1));
        getContentPane().add(operasional2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, -1, -1));
        getContentPane().add(modal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, -1));
        getContentPane().add(penghasilan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));
        getContentPane().add(operasional3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, -1));
        getContentPane().add(modal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, -1, -1));
        getContentPane().add(penghasilan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, -1, -1));
        getContentPane().add(operasional4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, -1, -1));
        getContentPane().add(modal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 540, -1, -1));
        getContentPane().add(u11txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));
        getContentPane().add(u12txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));
        getContentPane().add(u13txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));
        getContentPane().add(u15txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));
        getContentPane().add(u14txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, 30));
        getContentPane().add(u21txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));
        getContentPane().add(u22txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));
        getContentPane().add(u23txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, -1, -1));
        getContentPane().add(u24txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, -1, -1));
        getContentPane().add(u25txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 30, 30));
        getContentPane().add(u31txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, -1, -1));
        getContentPane().add(u33txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, -1, -1));
        getContentPane().add(u32txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, -1, -1));
        getContentPane().add(u34txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, -1, -1));
        getContentPane().add(u35txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 670, -1, -1));
        getContentPane().add(u41txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, -1, 20));
        getContentPane().add(u42txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, -1, -1));
        getContentPane().add(u43txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 620, -1, -1));
        getContentPane().add(u44txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, -1, -1));
        getContentPane().add(u45txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 670, -1, -1));

        kendaraanTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kendaraanTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kendaraanTxt.setText("0");
        getContentPane().add(kendaraanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 30, 30));

        propertyTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        propertyTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertyTxt.setText("0");
        getContentPane().add(propertyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametrpl/gambar/Halaman Main New.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        b_buatUsaha1.setText("buat");
        b_buatUsaha1.setBorderPainted(false);
        b_buatUsaha1.setContentAreaFilled(false);
        getContentPane().add(b_buatUsaha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 110, 30));

        b_buatUsaha2.setText("buat");
        b_buatUsaha2.setBorderPainted(false);
        b_buatUsaha2.setContentAreaFilled(false);
        getContentPane().add(b_buatUsaha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 295, 110, 40));

        b_buatUsaha3.setText("buat");
        b_buatUsaha3.setBorderPainted(false);
        b_buatUsaha3.setContentAreaFilled(false);
        getContentPane().add(b_buatUsaha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 110, 40));

        b_buatUsaha4.setText("buat");
        b_buatUsaha4.setContentAreaFilled(false);
        b_buatUsaha4.setDefaultCapable(false);
        getContentPane().add(b_buatUsaha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 595, 110, 30));

        b_nextTurn.setText("next turn");
        b_nextTurn.setBorderPainted(false);
        b_nextTurn.setContentAreaFilled(false);
        getContentPane().add(b_nextTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 6, 130, 130));

        b_usaha.setText("usaha");
        b_usaha.setBorderPainted(false);
        b_usaha.setContentAreaFilled(false);
        b_usaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_usahaActionPerformed(evt);
            }
        });
        getContentPane().add(b_usaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 130));

        b_bank.setText("bank");
        b_bank.setBorderPainted(false);
        b_bank.setContentAreaFilled(false);
        getContentPane().add(b_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 235, 150, 130));

        b_dealer.setText("dealer");
        b_dealer.setBorderPainted(false);
        b_dealer.setContentAreaFilled(false);
        getContentPane().add(b_dealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 395, 160, 130));

        b_property.setText("property");
        b_property.setBorderPainted(false);
        b_property.setContentAreaFilled(false);
        getContentPane().add(b_property, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 140, 130));

        aa.setText("aa");
        aa.setBorderPainted(false);
        aa.setContentAreaFilled(false);
        aa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 308, 50, 50));

        ab.setText("ab");
        ab.setBorderPainted(false);
        ab.setContentAreaFilled(false);
        getContentPane().add(ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, 50));

        ac.setText("ac");
        ac.setBorderPainted(false);
        ac.setContentAreaFilled(false);
        getContentPane().add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 308, 50, 50));

        ad.setText("ad");
        ad.setBorderPainted(false);
        ad.setContentAreaFilled(false);
        getContentPane().add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 358, 50, 50));

        ae.setText("ae");
        ae.setBorderPainted(false);
        ae.setContentAreaFilled(false);
        getContentPane().add(ae, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 358, -1, 50));

        ba.setText("ba");
        ba.setBorderPainted(false);
        ba.setContentAreaFilled(false);
        getContentPane().add(ba, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 60, 50));

        bb.setText("bb");
        bb.setBorderPainted(false);
        bb.setContentAreaFilled(false);
        getContentPane().add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 50, 50));

        bc.setText("bc");
        bc.setBorderPainted(false);
        bc.setContentAreaFilled(false);
        getContentPane().add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, -1, 40));

        bd.setText("bd");
        bd.setBorderPainted(false);
        bd.setContentAreaFilled(false);
        getContentPane().add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 358, -1, 50));

        be.setText("be");
        be.setBorderPainted(false);
        be.setContentAreaFilled(false);
        getContentPane().add(be, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 358, -1, 50));

        ca.setText("ca");
        ca.setBorderPainted(false);
        ca.setContentAreaFilled(false);
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, -1, 38));

        cb.setText("cb");
        cb.setBorderPainted(false);
        cb.setContentAreaFilled(false);
        getContentPane().add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, -1, 38));

        cc.setText("cc");
        cc.setBorderPainted(false);
        cc.setContentAreaFilled(false);
        getContentPane().add(cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, -1, 38));

        cd.setText("cd");
        cd.setBorderPainted(false);
        cd.setContentAreaFilled(false);
        getContentPane().add(cd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 660, -1, 38));

        ce.setText("ce");
        ce.setBorderPainted(false);
        ce.setContentAreaFilled(false);
        getContentPane().add(ce, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, -1, 38));

        da.setText("da");
        da.setBorderPainted(false);
        da.setContentAreaFilled(false);
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, -1, 38));

        db.setText("db");
        db.setBorderPainted(false);
        db.setContentAreaFilled(false);
        getContentPane().add(db, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, -1, 38));

        dc.setText("dc");
        dc.setBorderPainted(false);
        dc.setContentAreaFilled(false);
        getContentPane().add(dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 608, 50, 40));

        dd.setText("dd");
        dd.setBorderPainted(false);
        dd.setContentAreaFilled(false);
        getContentPane().add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, 50, 38));

        de.setText("de");
        de.setBorderPainted(false);
        de.setContentAreaFilled(false);
        getContentPane().add(de, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 660, -1, 38));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_usahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_usahaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_usahaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanUsaha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanUsaha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanUsaha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanUsaha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanUsaha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fotokopi;
    private javax.swing.JButton aa;
    private javax.swing.JButton ab;
    private javax.swing.JButton ac;
    private javax.swing.JButton ad;
    private javax.swing.JButton ae;
    private javax.swing.JButton b_bank;
    private javax.swing.JButton b_buatUsaha1;
    private javax.swing.JButton b_buatUsaha2;
    private javax.swing.JButton b_buatUsaha3;
    private javax.swing.JButton b_buatUsaha4;
    private javax.swing.JButton b_dealer;
    private javax.swing.JButton b_nextTurn;
    private javax.swing.JButton b_property;
    private javax.swing.JButton b_usaha;
    private javax.swing.JButton ba;
    private javax.swing.JButton bb;
    private javax.swing.JButton bc;
    private javax.swing.JButton bd;
    private javax.swing.JButton be;
    private javax.swing.JButton ca;
    private javax.swing.JButton cb;
    private javax.swing.JButton cc;
    private javax.swing.JButton cd;
    private javax.swing.JButton ce;
    private javax.swing.JButton da;
    private javax.swing.JLabel danaTxt;
    private javax.swing.JButton db;
    private javax.swing.JButton dc;
    private javax.swing.JButton dd;
    private javax.swing.JButton de;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel kendaraanTxt;
    private javax.swing.JLabel modal1;
    private javax.swing.JLabel modal2;
    private javax.swing.JLabel modal3;
    private javax.swing.JLabel modal4;
    private javax.swing.JLabel operasional1;
    private javax.swing.JLabel operasional2;
    private javax.swing.JLabel operasional3;
    private javax.swing.JLabel operasional4;
    private javax.swing.JLabel penghasilan1;
    private javax.swing.JLabel penghasilan2;
    private javax.swing.JLabel penghasilan3;
    private javax.swing.JLabel penghasilan4;
    private javax.swing.JLabel penghasilanTxt;
    private javax.swing.JLabel propertyTxt;
    private javax.swing.JLabel turnTxt;
    private javax.swing.JLabel u11txt;
    private javax.swing.JLabel u12txt;
    private javax.swing.JLabel u13txt;
    private javax.swing.JLabel u14txt;
    private javax.swing.JLabel u15txt;
    private javax.swing.JLabel u21txt;
    private javax.swing.JLabel u22txt;
    private javax.swing.JLabel u23txt;
    private javax.swing.JLabel u24txt;
    private javax.swing.JLabel u25txt;
    private javax.swing.JLabel u31txt;
    private javax.swing.JLabel u32txt;
    private javax.swing.JLabel u33txt;
    private javax.swing.JLabel u34txt;
    private javax.swing.JLabel u35txt;
    private javax.swing.JLabel u41txt;
    private javax.swing.JLabel u42txt;
    private javax.swing.JLabel u43txt;
    private javax.swing.JLabel u44txt;
    private javax.swing.JLabel u45txt;
    // End of variables declaration//GEN-END:variables
}
